name: Package facetracker
on:
  push:
    tags:
      - v**
  workflow_dispatch:

jobs:
  build-windows:
    env:
      dist-path: dist/OpenSeeFace
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Create binary
        shell: cmd
        run: make_exe.bat
      - name: Move files for uploading
        shell: bash
        run: |
          mv dist/facetracker ${{ env.dist-path }}
      - name: Upload artifact
        uses: ./.github/actions/upload-dated-artifact
        with:
          name: windows
          path: dist

  build-unix:
    env:
      artifact-path: OpenSeeFace
      tar-path: OpenSeeFace.tar
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
          - name: mac
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Linux window/camera libs
        if: matrix.name == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxkbcommon-dev libxi-dev libxcursor-dev clang pkg-config
      - name: Create binary
        run: |
          chmod +x make_exe.sh
          ./make_exe.sh
      - name: Move files for uploading
        shell: bash
        run: |
          mv dist/facetracker ${{ env.artifact-path }}
          chmod +x ${{ env.artifact-path }}/facetracker
      - name: Pack files into tar
        run: tar -cvf ${{ env.tar-path }} ${{ env.artifact-path }}
      - name: Upload artifact
        uses: ./.github/actions/upload-dated-artifact
        with:
          name: ${{ matrix.name }}
          path: ${{ env.tar-path }}
